name1=int(5)
name2=int(3)
print (name1*name2)
name1=input("enter your age: ")
print ("your age is",name1)
name2=input("enter your mobileno : ")
print ("your mobile no is",name2)
name3=input("enter your email : ")
print ("this is your emial",name3)
name4=input("enter your password : ")
print ("is this you passwordnyno" + ":" +name4)     