# a = 10
# b =  2
# def function():
#     print(a)
#     print(b)
# function()

# a = 9
# def function ():
#    print(a)
# b = 2

# print(b)
# print(a)
# function()


# def red(): 
#     a = 2
#     B = 1
#     print(a)
#     print(B)

#     def blue():
#         nyno1 = 10
#         b = 2
#         print(nyno1 * b)
#         print(b)
#     blue()
    
#     def black():
#         nyno =4
#         nyno1 =3
#         print(nyno/nyno1)
#     black()


# red()


# a = 2
# def function():
#     global a
# a = 10
# print(a)
# function()
# a


# def red():
#  a= 1

# def blue():
#     nonlocal a
#     a = 2
#     b = 3
#     print(a)
#     print(b)


# blue()
# print(b)

# red()



a = "Good"
b = "Morning"
print( a +" "+ b )